//    Info<< "Constructing thermoCloud1" << endl;
//    basicThermoCloud thermoCloud1
//    (
//        "thermoCloud1",
//        rho,
//        U,
//        g,
//        thermo
//    );

    Info<< "Constructing kinematicCloud1" << endl;
    basicKinematicCloud kinematicCloud1
    (
        "kinematicCloud1",
        rho, 
        U,
        mu,
        g
    );

    Info<< "Constructing kinematicCloud2" << endl;
    basicKinematicCloud kinematicCloud2
    (
        "kinematicCloud2",
        rho, 
        U,
        mu,
        g
    );
    
    Info<< "Constructing kinematicCloud3" << endl;
    basicKinematicCloud kinematicCloud3
    (
        "kinematicCloud3",
        rho, 
        U,
        mu,
        g
    );
    
    Info<< "Constructing kinematicCloud4" << endl;
    basicKinematicCloud kinematicCloud4
    (
        "kinematicCloud4",
        rho, 
        U,
        mu,
        g
    );
    
    Info<< "Constructing kinematicCloud5" << endl;
    basicKinematicCloud kinematicCloud5
    (
        "kinematicCloud5",
        rho, 
        U,
        mu,
        g
    );
